### ISSUE TITLE
Cannot install the request_ftp dependency

### ISSUE THREAD

**Issue by georgiana-b** [NextGeoss/nextgeoss-deadoralive#1]
I was unable to install this package because it has a dependency on `request_ftp`. According to my version of pip, that doesn't seem to exist.

![image](https://user-images.githubusercontent.com/8862002/78804617-a8268580-79c0-11ea-98b4-7038a1cb9cf8.png)

I was also unable to find that library [on pypi](https://pypi.org/search/?q=request_ftp).
Was this a typo?

**Comment by joaandrade** [comment]
@ToniDSHG can you provide feedback on this issue?

**Comment by ToniDSHG** [comment]
Hi, there is mistake in setup.py, the real name for the library is requests_ftp. An 's' is missed.

**Comment by georgiana-b** [comment]
@ToniDSHG  @joaandrade  Could you please push the change so that I can use this library?

**Comment by joaandrade** [comment]
@georgiana-b the commit was already done

**Comment by georgiana-b** [comment]
Solved in https://github.com/NextGeoss/nextgeoss-deadoralive/commit/66138b807f2cfeed46587172fc3cc6da399b8ddb
