### ISSUE TITLE
Config missing 

### ISSUE THREAD

**Issue by georgiana-b** [NextGeoss/nextgeoss-deadoralive#2]
I installed the library as described in [the README](https://github.com/NextGeoss/nextgeoss-deadoralive#usage)

However, when I'm trying to run the command  `deadoralive --url <my_site> --apikey <api_key>` I get the following error:

```

Traceback (most recent call last):
  File "/Users/g/.virtualenvs/testdeadoralive/bin/deadoralive", line 11, in <module>
    load_entry_point('deadoralive', 'console_scripts', 'deadoralive')()
  File "/Users/g/.virtualenvs/testdeadoralive/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/g/.virtualenvs/testdeadoralive/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/g/.virtualenvs/testdeadoralive/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/g/.virtualenvs/testdeadoralive/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/g/.virtualenvs/testdeadoralive/src/nextgeoss-deadoralive/deadoralive/deadoralive.py", line 23, in <module>
    import ckanext.deadoralive.config as config
```

And indeed there seems to be no config file. I guess you forgot to push it? 

Also, could you please make to go through the process a user would have to follow and make sure that the library can be installed and used? 
Thanks a lot! 🙏

**Comment by joaandrade** [comment]
@ToniDSHG can you please take a look at this issue?

**Comment by ToniDSHG** [comment]
@georgiana-b , are you running the ckan server with the extension installed?

**Comment by georgiana-b** [comment]
@ToniDSHG  Yes, I do have the extension installed but the main issue here is the way you are [importing the config](https://github.com/NextGeoss/nextgeoss-deadoralive/blob/master/deadoralive/deadoralive.py#L23). 

If you want this to be a separate service that can even run by itself on a different server, [like the README is saying](https://github.com/NextGeoss/nextgeoss-deadoralive#running-the-link-checker-on-a-different-machine), you can't assume they run in the same folder. If you want [that](https://github.com/NextGeoss/nextgeoss-deadoralive/blob/master/deadoralive/deadoralive.py#L23) to work you're gonna have to install [`ckanext-nextgeossdeadoralive`](https://github.com/NextGeoss/ckanext-nextgeossdeadoralive) as a dependency for this library. 

Although to be honest I don't see the reasoning to hardcode them like that [in the extension](https://github.com/NextGeoss/ckanext-nextgeossdeadoralive/blob/91510e35ecbf66abf65a32c87c1d1fd4db04d746/ckanext/deadoralive/config.py). It would be much more intuitive and secure to define those credentials through an .env file in this project or to pass them like command line arguments rather than pushing them on GitHub in a public repo, no?

**Comment by georgiana-b** [comment]
@ToniDSHG Apologies for my passive aggressive comment above. It was all well intended. Feel free to proceed as you see fit. Just make sure to document it so that I can install and use the library according to the instructions.

**Comment by joaandrade** [comment]
@ToniDSHG one other issue are the user/password pairs included in the config file (e.g. [here](https://github.com/NextGeoss/ckanext-nextgeossdeadoralive/blob/91510e35ecbf66abf65a32c87c1d1fd4db04d746/ckanext/deadoralive/config.py#L22))
Please replace the credentials by dummy user/pass in the config file and add to the instructions that the real user/password of some providers need to be added during the installation. Remember that anyone can access this repo, so no credenttials in the code.

**Comment by ToniDSHG** [comment]
Hi @georgiana-b ! Don't worry, I think you are right .
Tomorrow i'll take a look to this issue. Any change or decision we make I'll notice you.
But I'm sure that we'll change this and add more information to Readme file

**Comment by ToniDSHG** [comment]
HI @georgiana-b , i think ive found the error, I'll fix it for tomorrow.
About the problem with the the user/password pairs included in the config file, we are thinking how to change this.

**Comment by michellecbox** [comment]
hi @ToniDSHG any upates here? thanks!

**Comment by ToniDSHG** [comment]
I'm waiting for the approval of the changes. Because I think we can do without the config file. I hope to upload the changes today or tomorrow

**Comment by ToniDSHG** [comment]
I have uploaded a temporary solution with changes for authentication. Now you have to pass the username and password needed for the cmems ftp through the command line. You have the updated information in the README.
Also this is temporary, we know that maybe there will be more providers that will need user/pass, but it will be an issue that we will discuss later, because now we are wuite busy with another project.
If you have other issue with the installation, please notify me.

**Comment by georgiana-b** [comment]
@ToniDSHG We're all very busy but we still need to provide a workable and reasonably sound solution to this dead or alive checker.

Besides the shortcomings that you already mentioned, the command line arguments are also very vague. `user` and `passw` could mean anything. There is also no `--help` for the CLI telling the user what those parameters mean so imagine when someone is going to have to deploy/debug this on a server one day, how they will not know how to use this. 

Could you please at least rename the command line arguments to something more clear like `cmems-user` and `cmems-pass`?

And also could you stop pushing things directly to master? Just open a PR that I can review, merge and close this issue. Let's behave like civilised programmers shall we?

**Comment by georgiana-b** [comment]
For example in [this case](https://github.com/NextGeoss/nextgeoss-deadoralive/commit/66138b807f2cfeed46587172fc3cc6da399b8ddb) you forgot to fix the `requests_ftp` typo in the `dev_requirements` file too but I couldn't tell you that before merging because there was no PR.

**Comment by ToniDSHG** [comment]
I have updated the changes you told about. I have renamed the command line arguments and added some info to -h option.

**Comment by joaandrade** [comment]
@georgiana-b is this issue solved?

**Comment by georgiana-b** [comment]
@ToniDSHG Running the command with the new parameters 

```
deadoralive --cmemsuser <your_user> --cmemspasw <your_pass> --url <your_site> --apikey <your_api_key>
```

leads to an error because you're still expecting for `user` and `pasw` [in the code](https://github.com/NextGeoss/nextgeoss-deadoralive/blob/34c28bfda3fa91ff3cfa9e185828fc39654a8c18/deadoralive/deadoralive.py#L229).

Please make sure the code is working end-to-end and open a PR.

**Comment by georgiana-b** [comment]
Also, if the library is built for Python 2.7 as the REAME [is saying](https://github.com/NextGeoss/nextgeoss-deadoralive#requirements) pls make sure you define versions of the dependencies that have Python 2.7 support. For example I had to set up these versions in order install the dev requirements

```
nose
mock==3.0.5
httpretty==0.9.7
coverage
requests_ftp
```

But the others probably need a version freeze too to make sure the library doesn't break in the future if it's not being maintained. 

You can check the revision history on pip to see which versions have Python 2 support.
For example: https://pypi.org/project/httpretty/0.9.7/#history

**Comment by joaandrade** [comment]
@ToniDSHG can you please take a look to the last comment?

**Comment by georgiana-b** [comment]
@ToniDSHG This fix is particularly important as the library can't be used atm:
https://github.com/NextGeoss/nextgeoss-deadoralive/issues/2#issuecomment-645378997

**Comment by ToniDSHG** [comment]
Hi @georgiana-b , Im a lit busy with other project, as soon as i can, iIl review it

**Comment by georgiana-b** [comment]
@ToniDSHG This is my last day on this project. Could you please prioritise this one instead?

**Comment by ToniDSHG** [comment]
@georgiana-b , I've uploaded new changes, now you should not have problems

**Comment by georgiana-b** [comment]
Thanks a lot @ToniDSHG!

**Comment by joaandrade** [comment]
@georgiana-b @JGulic any updates on this issue?
